name: Lint Markdown

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            **/*.md
          config: .markdownlint.yaml

